// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/auth.proto

package authpb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OAuth2 AccessToken
	AccessToken   string `protobuf:"bytes,11,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户 ID（Snowflake ID 字符串）
	UserId string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	// 角色名称: SUPER_ADMIN / ADMIN / PLAYER
	RoleName string `protobuf:"bytes,13,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	// 是否被封禁
	HasBan        bool `protobuf:"varint,14,opt,name=has_ban,json=hasBan,proto3" json:"has_ban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ValidateTokenResponse) GetHasBan() bool {
	if x != nil {
		return x.HasBan
	}
	return false
}

type GetUserRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（Snowflake ID 字符串）
	UserId        string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoleRequest) Reset() {
	*x = GetUserRoleRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleRequest) ProtoMessage() {}

func (x *GetUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleRequest.ProtoReflect.Descriptor instead.
func (*GetUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 角色名称
	RoleName string `protobuf:"bytes,11,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	// 是否被封禁
	HasBan        bool `protobuf:"varint,12,opt,name=has_ban,json=hasBan,proto3" json:"has_ban,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRoleResponse) Reset() {
	*x = GetUserRoleResponse{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleResponse) ProtoMessage() {}

func (x *GetUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleResponse.ProtoReflect.Descriptor instead.
func (*GetUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRoleResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetUserRoleResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GetUserRoleResponse) GetHasBan() bool {
	if x != nil {
		return x.HasBan
	}
	return false
}

type CheckPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（Snowflake ID 字符串）
	UserId string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 允许的角色列表
	AllowedRoles  []string `protobuf:"bytes,12,rep,name=allowed_roles,json=allowedRoles,proto3" json:"allowed_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetAllowedRoles() []string {
	if x != nil {
		return x.AllowedRoles
	}
	return nil
}

type CheckPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 是否通过权限检查
	Allowed bool `protobuf:"varint,11,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// 用户的实际角色
	RoleName      string `protobuf:"bytes,12,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CheckPermissionResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type GetUserInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（Snowflake ID 字符串）
	UserId        string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户 ID（Snowflake ID 字符串）
	UserId string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	// GameProfile 列表
	GameProfiles  []*GameProfileInfo `protobuf:"bytes,13,rep,name=game_profiles,json=gameProfiles,proto3" json:"game_profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetUserInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResponse) GetGameProfiles() []*GameProfileInfo {
	if x != nil {
		return x.GameProfiles
	}
	return nil
}

type GameProfileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GameProfile UUID
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// MC 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 权限组名称
	GroupName     string `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameProfileInfo) Reset() {
	*x = GameProfileInfo{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameProfileInfo) ProtoMessage() {}

func (x *GameProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameProfileInfo.ProtoReflect.Descriptor instead.
func (*GameProfileInfo) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GameProfileInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GameProfileInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GameProfileInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x13frontleaves.auth.v1\x1a\x0flink/base.proto\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\v \x01(\tR\vaccessToken\"\xbc\x01\n" +
	"\x15ValidateTokenResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\f \x01(\tR\busername\x12\x1b\n" +
	"\trole_name\x18\r \x01(\tR\broleName\x12\x17\n" +
	"\ahas_ban\x18\x0e \x01(\bR\x06hasBan\"-\n" +
	"\x12GetUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\"\x85\x01\n" +
	"\x13GetUserRoleResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x1b\n" +
	"\trole_name\x18\v \x01(\tR\broleName\x12\x17\n" +
	"\ahas_ban\x18\f \x01(\bR\x06hasBan\"V\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12#\n" +
	"\rallowed_roles\x18\f \x03(\tR\fallowedRoles\"\x8a\x01\n" +
	"\x17CheckPermissionResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x18\n" +
	"\aallowed\x18\v \x01(\bR\aallowed\x12\x1b\n" +
	"\trole_name\x18\f \x01(\tR\broleName\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\"\xcf\x01\n" +
	"\x13GetUserInfoResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\f \x01(\tR\busername\x12I\n" +
	"\rgame_profiles\x18\r \x03(\v2$.frontleaves.auth.v1.GameProfileInfoR\fgameProfiles\"`\n" +
	"\x0fGameProfileInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"group_name\x18\x03 \x01(\tR\tgroupName2\xa7\x03\n" +
	"\vAuthService\x12f\n" +
	"\rValidateToken\x12).frontleaves.auth.v1.ValidateTokenRequest\x1a*.frontleaves.auth.v1.ValidateTokenResponse\x12`\n" +
	"\vGetUserRole\x12'.frontleaves.auth.v1.GetUserRoleRequest\x1a(.frontleaves.auth.v1.GetUserRoleResponse\x12l\n" +
	"\x0fCheckPermission\x12+.frontleaves.auth.v1.CheckPermissionRequest\x1a,.frontleaves.auth.v1.CheckPermissionResponse\x12`\n" +
	"\vGetUserInfo\x12'.frontleaves.auth.v1.GetUserInfoRequest\x1a(.frontleaves.auth.v1.GetUserInfoResponseBAZ?github.com/frontleaves-mc/frontleaves-yggleaf/proto/auth;authpbb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_auth_auth_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),    // 0: frontleaves.auth.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),   // 1: frontleaves.auth.v1.ValidateTokenResponse
	(*GetUserRoleRequest)(nil),      // 2: frontleaves.auth.v1.GetUserRoleRequest
	(*GetUserRoleResponse)(nil),     // 3: frontleaves.auth.v1.GetUserRoleResponse
	(*CheckPermissionRequest)(nil),  // 4: frontleaves.auth.v1.CheckPermissionRequest
	(*CheckPermissionResponse)(nil), // 5: frontleaves.auth.v1.CheckPermissionResponse
	(*GetUserInfoRequest)(nil),      // 6: frontleaves.auth.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),     // 7: frontleaves.auth.v1.GetUserInfoResponse
	(*GameProfileInfo)(nil),         // 8: frontleaves.auth.v1.GameProfileInfo
	(*generate.BaseResponse)(nil),   // 9: xBase.BaseResponse
}
var file_auth_auth_proto_depIdxs = []int32{
	9, // 0: frontleaves.auth.v1.ValidateTokenResponse.base_response:type_name -> xBase.BaseResponse
	9, // 1: frontleaves.auth.v1.GetUserRoleResponse.base_response:type_name -> xBase.BaseResponse
	9, // 2: frontleaves.auth.v1.CheckPermissionResponse.base_response:type_name -> xBase.BaseResponse
	9, // 3: frontleaves.auth.v1.GetUserInfoResponse.base_response:type_name -> xBase.BaseResponse
	8, // 4: frontleaves.auth.v1.GetUserInfoResponse.game_profiles:type_name -> frontleaves.auth.v1.GameProfileInfo
	0, // 5: frontleaves.auth.v1.AuthService.ValidateToken:input_type -> frontleaves.auth.v1.ValidateTokenRequest
	2, // 6: frontleaves.auth.v1.AuthService.GetUserRole:input_type -> frontleaves.auth.v1.GetUserRoleRequest
	4, // 7: frontleaves.auth.v1.AuthService.CheckPermission:input_type -> frontleaves.auth.v1.CheckPermissionRequest
	6, // 8: frontleaves.auth.v1.AuthService.GetUserInfo:input_type -> frontleaves.auth.v1.GetUserInfoRequest
	1, // 9: frontleaves.auth.v1.AuthService.ValidateToken:output_type -> frontleaves.auth.v1.ValidateTokenResponse
	3, // 10: frontleaves.auth.v1.AuthService.GetUserRole:output_type -> frontleaves.auth.v1.GetUserRoleResponse
	5, // 11: frontleaves.auth.v1.AuthService.CheckPermission:output_type -> frontleaves.auth.v1.CheckPermissionResponse
	7, // 12: frontleaves.auth.v1.AuthService.GetUserInfo:output_type -> frontleaves.auth.v1.GetUserInfoResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
