// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: link/base.proto

package xGrpcGenerate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseResponse 表示 gRPC 统一响应的元信息部分。
type BaseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求追踪标识（。
	Context string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// 输出标识（如 "Success"、"PARAMETER_ERROR"）。
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// 业务状态码（200 表示成功，其余与 xError.ErrorCode.Code 对应）。
	Code uint64 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	// 人类可读的描述信息。
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// 补充性错误详情，仅在错误场景下填充。
	ErrorMessage *string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	// 请求处理耗时（微秒），仅在调试模式下填充。
	Overhead      *int64 `protobuf:"varint,6,opt,name=overhead,proto3,oneof" json:"overhead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_link_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_link_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_link_base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *BaseResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *BaseResponse) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *BaseResponse) GetOverhead() int64 {
	if x != nil && x.Overhead != nil {
		return *x.Overhead
	}
	return 0
}

var File_link_base_proto protoreflect.FileDescriptor

const file_link_base_proto_rawDesc = "" +
	"\n" +
	"\x0flink/base.proto\x12\x05xBase\"\xd8\x01\n" +
	"\fBaseResponse\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x04R\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12(\n" +
	"\rerror_message\x18\x05 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12\x1f\n" +
	"\boverhead\x18\x06 \x01(\x03H\x01R\boverhead\x88\x01\x01B\x10\n" +
	"\x0e_error_messageB\v\n" +
	"\t_overheadB\x11Z\x0f.;xGrpcGenerateb\x06proto3"

var (
	file_link_base_proto_rawDescOnce sync.Once
	file_link_base_proto_rawDescData []byte
)

func file_link_base_proto_rawDescGZIP() []byte {
	file_link_base_proto_rawDescOnce.Do(func() {
		file_link_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_link_base_proto_rawDesc), len(file_link_base_proto_rawDesc)))
	})
	return file_link_base_proto_rawDescData
}

var file_link_base_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_link_base_proto_goTypes = []any{
	(*BaseResponse)(nil), // 0: xBase.BaseResponse
}
var file_link_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_link_base_proto_init() }
func file_link_base_proto_init() {
	if File_link_base_proto != nil {
		return
	}
	file_link_base_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_link_base_proto_rawDesc), len(file_link_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_link_base_proto_goTypes,
		DependencyIndexes: file_link_base_proto_depIdxs,
		MessageInfos:      file_link_base_proto_msgTypes,
	}.Build()
	File_link_base_proto = out.File
	file_link_base_proto_goTypes = nil
	file_link_base_proto_depIdxs = nil
}
